name: restaurant_pos_system
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # HTTP requests
  http: ^1.2.1
  
  # Local database
  sqflite: ^2.3.3+1
  
  # Navigation
  go_router: ^14.2.0
  
  # UI components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Date/time handling
  intl: ^0.19.0
  
  # Charts for analytics
  fl_chart: ^0.68.0
  
  # Animation
  lottie: ^3.1.2
  
  # Local storage
  shared_preferences: ^2.2.3
  
  # Path provider
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # REMOVED FONT ASSETS THAT DON'T EXIST
    - assets/images/logo/wizard_logo.png

  # REMOVED CUSTOM FONTS - Using system fonts instead
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto/Roboto-Regular.ttf