name: restaurant_pos_system
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # vibrations
  vibration: ^3.1.3
  # haptic_feedback: ^0.5.1+1

  # Native Splash Screen
  flutter_native_splash: ^2.4.6

  # State Management
  provider: ^6.1.2
  
  #Better image handling
  cached_network_image: ^3.4.1

  #Connectivity check
  connectivity_plus: 5.0.2

  #Lottie animations
  lottie: ^3.3.1

  #App Settings
  app_settings: ^6.1.1

  # HTTP requests
  http: ^1.2.1

  #UUID generation for order IDs
  uuid: ^4.5.1
  
  # Local database - Added Hive for offline storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  
  # Navigation
  go_router: ^14.2.0

  #Foundation library
  foundation: ^0.0.5
  
  # UI components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Date/time handling
  intl: ^0.20.2

  # International phone field
  intl_phone_field: ^3.2.0
  
  # Charts for analytics
  fl_chart: ^1.0.0

  #URL Launcher
  url_launcher: ^6.3.2
  
  # Local storage
  shared_preferences: ^2.2.3
  
  # Path provider
  path_provider: ^2.1.3

  #QR Code Generation
  qr_flutter: ^4.1.0
  
  # PDF Generation and Sharing
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  # web: false
  image_path: "assets/logo/restaurant_pos_system_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/wizard_logo.png
